local moonstone = require("moonstone")
moonstone.start()
moonstone.md.h1("Moonstone")
moonstone.md.p("A Framework To Build Webpages And Websites With Lua Programming Language!!!")
moonstone.md.h3("Upcoming:")
moonstone.md.checkbox("Full Markdown API",true)
moonstone.md.checkbox("Full Javascript API",false)
moonstone.md.checkbox("Full PHP API",false)
moonstone.finish() 