local moonstone = require("moonstone") 
moonstone.begin() 
moonstone.html("begin")
moonstone.head("begin")
moonstone.title("Webpage Made With Lua")
moonstone.head("end")
moonstone.body("begin")
moonstone.p("Hello World!!!")
moonstone.body("end")
moonstone.html("end")
moonstone.endwebpage()